# Generated by Django 3.2.13 on 2022-06-09 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='data_added',
            new_name='posted_date',
        ),
    ]
